name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  build-and-release:
    uses: containifyci/.github/.github/workflows/release.yml@v1
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    secrets: inherit
